# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnlhLzsThRvKThHx6vV53T888oafghLD
"""

# All imports go here.
import re

'''
  Declaring a long string the Pythonic way
  # @ discuss.python.org/t/pythonic-way-of-printing-multi-line-strings/19681
'''

speech_from_the_great_dictator = """
We have developed speed, but we have shut ourselves in.
Machinery that gives abundance has left us in want.
Our knowledge has made us cynical.
Our cleverness, hard and unkind.
We think too much and feel too little.
More than machinery we need humanity.
More than cleverness we need kindness and gentleness."""

# Quick test to verify that the variable above prints out the correct speech.
# Print is one of the fastest and dirtiest ways to test your code.
# @https://jasondeden.medium.com/debugging-code-issues-using-print-statements-and-simple-test-data-84d9487d1254
print(speech_from_the_great_dictator)

'''
  Functions related to:
  1. Count the number of words in a text.
  @ https://www.geeksforgeeks.org/python/python-program-to-count-words-in-a-sentence
'''

def count_words_in_sentence(sentence: str):
  if len(sentence) == 0: # Some simple error handling, since we want to safeguard the code from doing weird things in case of silly user input.
    return print("This sentence is non-existent.")
  else:
    word_count = len(sentence.split()) # Splits the sentence into separate list items @https://www.w3schools.com/python/ref_string_split.asp.
    word_count_to_string = str(word_count) # Convert the word count into a string.
    return print(f"This entire text contains {word_count_to_string} words.") # @https://www.datacamp.com/tutorial/python-f-string

# Helper function to reuse later when printing is not necessary.
def return_word_count(sentence: str):
  if len(sentence) == 0: # Some simple error handling.
    return
  else:
    return len(sentence.split()) # Splitting the sentence prints out each word one by one.

'''
 Functions related to:
 2. Count the number of sentences in a text.
 @ https://stackoverflow.com/questions/29166774/count-number-of-sentences-in-paragraph, while also using:
 https://regex101.com to help build an appropriate regex.
'''

def count_number_of_sentences(text: str):
  if len(text) == 0: # Some simple error handling to safeguard the code from silly user input.
    return print("This text is non-existent.")
  else:
    sentence_count = len(re.findall(r'[\.]', text)) # We are just considering full stops at this point.
    sentence_count_to_string = str(sentence_count) # Convert the word count into a string.
    return print(f"This text contains {sentence_count_to_string} sentences.")

# Helper function to reuse later when printing is not necessary.
def count_sentences_and_return_int(text: str):
  if len(text) == 0: # Some simple error handling to prevent strange things from happening in case of weird user input.
    return
  else:
    return len(re.findall(r'[\.]', text))

'''
  Functions related to:
  3. Sort the sentences according to their number of words.
  Built on knowledge garnered from the previous two functions.
'''
def get_word_count_of_each_sentence_in_a_text(text: str):
 sentences_list = text.split('.') # Split up sentences by full stop.
 number_count = [] # Create an empty number count list
 for sentence in sentences_list:
  count = return_word_count(sentence) # Get the word count of each sentence.
  if count != None: # Only append values to the list that are, in fact, integers.
    number_count.append(return_word_count(sentence)) # Append the number of words to the number count list.
 return number_count # Return the number count list.


def sorted_number_of_words_in_each_sentence(sorted_list):
  sentence_number = 0 # Used to count the number of sentences.
  sentences_list = [] # Empty sentences list.
  for number in sorted_list:
    sentence_number += 1 # Increase the number of sentences while the loop is still running.
    if sentence_number == 2:
      sentences_list.append(f"The {sentence_number}nd sentence contains {number} words.") # Append this to the previously created empty list.
    else:
      sentences_list.append(f"The {sentence_number}th sentence contains {number} words.") # Always account for grammar.
  return sentences_list

def determine_length_of_sentences(text:str):
  list_of_sentence_counts = get_word_count_of_each_sentence_in_a_text(text)
  sorted_numbers = sorted(list_of_sentence_counts, reverse=True) # Sorts and returns a list @https://stackoverflow.com/questions/7301110/why-does-return-list-sort-return-none-not-the-list
  list_to_print = sorted_number_of_words_in_each_sentence(sorted_numbers) # Use the sorted list to create a list that can be used for printing.
  for sentence in list_to_print:
    print(sentence)

'''
  Functions related to:
  4. Identify and sort the longest words in the text.
  Built on knowledge garnered from previous functions and
  @https://stackoverflow.com/questions/70169259/find-five-longest-words-in-a-list-in-python-and-order-them-in-alphabetical-order
  @https://stackoverflow.com/questions/2277352/split-a-string-at-uppercase-letters For the hint on how to deal with merged characters.
'''

def get_five_longest_words(text: str):
  cleaned_up_text = re.sub("[^a-zA-Z ']+", r"\n", text.lower())  # Use a regex to filter out any undesirable elements, as we only want to focus on alphabetical characters.
  split_sentences = cleaned_up_text.split() # Split the text into sentences.
  remove_redundancies = [] # Create an empty list.
  for word in split_sentences:
    if word not in remove_redundancies: # Check if the word is already in the list.
      remove_redundancies.append(word)
  return sorted(sorted(remove_redundancies, key=len)[-5:]) # List slicing allows for specific elements to be retrieved from a list @https://www.geeksforgeeks.org/python/python-list-slicing.

def print_out_five_longest_words(text: str):
  position = 0 # Placeholder for iterating the position of the list.
  list_of_longest_words = get_five_longest_words(text)
  for word in list_of_longest_words:
    position +=1
    if position == 2:
      print(f"The {position}nd largest word is {word}.") # As always, account for grammar for the sake of readability.
    else:
      print(f"The {position}th largest word is {word}.")

# Outputs

# Count the number of words in a whole sentence.
count_words_in_sentence(speech_from_the_great_dictator)

# Count the number of sentences in a given text.
count_number_of_sentences(speech_from_the_great_dictator)

# Determine the length of each sentence in a text and then print them out from largest to smallest.
determine_length_of_sentences(speech_from_the_great_dictator)

# Print out the five longest words in a given text.
print_out_five_longest_words(speech_from_the_great_dictator)
