# -*- coding: utf-8 -*-
"""Feline Maps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ee3fXlL79ZscsLlUhiDApl-_g2NwnVnn
"""

# Download the necessary libraries
!pip install pandas
!pip install matplotlib
!pip install geopandas
!pip install contextily

# Import the necessary modules
import geopandas as gpd
import contextily as cx
import pandas as pd
import matplotlib.pyplot as plt

cat_data = pd.read_csv("/content/cat_gis.csv")
cat_data.head(n=10)

# Rename columns @ https://stackoverflow.com/questions/11346283/renaming-column-names-in-pandas
cat_data = cat_data.rename(columns={'Location': 'location', 'Latitude': 'latitude', "Longtitude": "longitude"})
cat_data.head(n=10)

# Prepare data for map plotting
cat_graph = gpd.GeoDataFrame(cat_data, geometry=gpd.points_from_xy(cat_data.longitude, cat_data.latitude), crs="EPSG:4326")
cat_graph = cat_graph.to_crs(epsg=3857) # For reference: https://pygis.io/docs/d_crs_what_is_it.html

cat_graph.plot(figsize = (5, 5)) # No map yet!

#  Reusable function (for the lazy)
def draw_graph(provider, title, provider_map_wanted):
  fig, ax = plt.subplots(figsize=(8, 8))
  cat_graph.plot(ax=ax, color='blue', markersize=50, alpha=0.6, edgecolor='k')
  if provider_map_wanted:
   cx.add_basemap(ax, source=provider)
  else:
    cx.add_basemap(ax)
  plt.title(title)
  plt.xlabel("Longitude")
  plt.ylabel("Latitude")
  plt.show()

# Draw the graph (using Open Street Map) @https://contextily.readthedocs.io/en/latest/providers_deepdive.html
draw_graph(cx.providers.OpenStreetMap.Mapnik, "Nana's Feline Travels", True)

# Draw the graph (using the Base Map) @https://contextily.readthedocs.io/en/latest/providers_deepdive.html
draw_graph(cx.providers.OpenStreetMap.Mapnik, "Nana's Feline Travels", False)

# Draw the graph (using NASA-related imagery) @https://contextily.readthedocs.io/en/latest/providers_deepdive.html
draw_graph(cx.providers.NASAGIBS.ViirsEarthAtNight2012, "Nana's Feline Travels", True)